-- Sequence Message Queue
-- Created: 2026-02-09 for RS-EMAIL-007
-- Purpose: Queue messages generated by sequence processor for review before sending

CREATE TABLE IF NOT EXISTS sequence_message_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  follow_up_id UUID REFERENCES contact_follow_ups(id) ON DELETE SET NULL,
  contact_id UUID REFERENCES contacts(id) ON DELETE CASCADE,
  business_id UUID REFERENCES businesses(id) ON DELETE CASCADE,
  channel TEXT NOT NULL CHECK (channel IN ('sms', 'email')),
  recipient TEXT NOT NULL, -- email address or phone number
  subject TEXT, -- for email only
  message TEXT NOT NULL,
  step_order INT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'sent', 'failed', 'cancelled')),
  approved_at TIMESTAMPTZ,
  approved_by UUID,
  sent_at TIMESTAMPTZ,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sequence_message_queue_status ON sequence_message_queue(status);
CREATE INDEX IF NOT EXISTS idx_sequence_message_queue_contact ON sequence_message_queue(contact_id);
CREATE INDEX IF NOT EXISTS idx_sequence_message_queue_business ON sequence_message_queue(business_id);
CREATE INDEX IF NOT EXISTS idx_sequence_message_queue_created ON sequence_message_queue(created_at);

-- Enable RLS
ALTER TABLE sequence_message_queue ENABLE ROW LEVEL SECURITY;

-- RLS Policies (service role for backend processing, authenticated users for their own business)
CREATE POLICY "Service role full access to queue" ON sequence_message_queue
  FOR ALL USING (auth.role() = 'service_role');

-- Authenticated users can view queue entries related to their contacts
CREATE POLICY "Authenticated users view queue" ON sequence_message_queue
  FOR SELECT USING (auth.role() = 'authenticated');

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_sequence_queue_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_sequence_message_queue_timestamp ON sequence_message_queue;
CREATE TRIGGER update_sequence_message_queue_timestamp
  BEFORE UPDATE ON sequence_message_queue
  FOR EACH ROW EXECUTE FUNCTION update_sequence_queue_timestamp();

-- Comment for documentation
COMMENT ON TABLE sequence_message_queue IS 'Queued messages from follow-up sequences awaiting approval or processing';
COMMENT ON COLUMN sequence_message_queue.status IS 'pending=awaiting review, approved=ready to send, sent=delivered, failed=error, cancelled=rejected';
